(function () {
  'use strict';

  const text = (en, ms) => ({ en, ms });
  const topic = (chapterId, id, title, visualType, purpose, howToRead, whenToUse, commonMistakes, options = {}) => ({
    id, chapterId, title, visualType, purpose, howToRead, whenToUse, commonMistakes,
    aliases: options.aliases || [], comparisons: options.comparisons || [], explorerRefs: options.explorerRefs || [],
    covers: options.covers || [], sources: options.sources || ['ttte1113', 'omg-uml', chapterId === 'class' ? 'drawio-class' : ['sequence', 'fragments'].includes(chapterId) ? 'drawio-sequence' : 'drawio'],
  });
  const question = (chapterId, id, prompt, choices, answer, explanation) => ({ id, chapterId, prompt, choices, answer, explanation });

  const chapters = [
    { id: 'orientation', icon: 'compass', title: text('Diagram orientation', 'Orientasi rajah'), summary: text('Learn what a diagram is trying to say before reading its symbols.', 'Kenal pasti tujuan rajah sebelum membaca simbolnya.') },
    { id: 'connectors', icon: 'git-branch', title: text('Connector cheat sheet', 'Panduan penyambung'), summary: text('Compare line patterns, arrowheads, diamonds and cardinality marks.', 'Bandingkan corak garisan, kepala anak panah, berlian dan tanda kardinaliti.') },
    { id: 'usecase', icon: 'users', title: text('Use Case diagrams', 'Rajah Kes Guna'), summary: text('Read actors, system goals and include/extend relationships.', 'Baca aktor, matlamat sistem serta hubungan include/extend.') },
    { id: 'sequence', icon: 'list-tree', title: text('Sequence diagrams', 'Rajah Jujukan'), summary: text('Follow participants and messages from top to bottom through time.', 'Ikuti peserta dan mesej dari atas ke bawah mengikut masa.') },
    { id: 'fragments', icon: 'panels-top-left', title: text('Sequence fragments', 'Fragmen Jujukan'), summary: text('Understand alternatives, optional paths, loops and parallel work.', 'Fahami laluan alternatif, pilihan, gelung dan kerja selari.') },
    { id: 'activity', icon: 'workflow', title: text('Activity diagrams', 'Rajah Aktiviti'), summary: text('Trace workflow, decisions, parallel branches and responsibility lanes.', 'Jejaki aliran kerja, keputusan, cabang selari dan lorong tanggungjawab.') },
    { id: 'class', icon: 'boxes', title: text('Class diagrams', 'Rajah Kelas'), summary: text('Read class structure, multiplicity and ownership relationships.', 'Baca struktur kelas, kepelbagaian dan hubungan pemilikan.') },
    { id: 'erd', icon: 'database', title: text('ERD and data', 'ERD dan data'), summary: text('Understand database keys, optionality and table cardinality.', 'Fahami kekunci pangkalan data, opsyenaliti dan kardinaliti jadual.') },
    { id: 'architecture', icon: 'network', title: text('Architecture and data flow', 'Seni bina dan aliran data'), summary: text('Separate structural dependencies from runtime data movement.', 'Bezakan kebergantungan struktur daripada pergerakan data masa jalan.') },
    { id: 'state', icon: 'repeat-2', title: text('State Diagram essentials', 'Asas Rajah Keadaan'), summary: text('Model states and the events that trigger transitions.', 'Modelkan keadaan dan peristiwa yang mencetuskan peralihan.') },
  ];

  const topics = [
    topic('orientation', 'static-dynamic', text('Static vs behavioural', 'Statik lwn tingkah laku'), 'static-dynamic',
      text('A structural diagram shows what exists; a behavioural diagram shows what happens over time.', 'Rajah struktur menunjukkan apa yang wujud; rajah tingkah laku menunjukkan apa yang berlaku mengikut masa.'),
      text('Ask whether position represents structure or time. Class and ERD views are static; sequence and activity views are behavioural.', 'Tanya sama ada kedudukan mewakili struktur atau masa. Rajah kelas dan ERD adalah statik; rajah jujukan dan aktiviti adalah tingkah laku.'),
      text('Use this distinction before interpreting any arrow.', 'Gunakan perbezaan ini sebelum mentafsir sebarang anak panah.'),
      text('Do not assume an arrow has the same meaning in every diagram family.', 'Jangan anggap anak panah mempunyai maksud yang sama dalam semua keluarga rajah.'),
      { aliases: ['static', 'dynamic', 'structural', 'behavioural', 'behavioral', 'statik', 'dinamik', 'tingkah laku'] }),
    topic('orientation', 'reading-direction', text('Reading direction', 'Arah bacaan'), 'reading-direction',
      text('Diagram families encode order differently.', 'Keluarga rajah mengekod urutan dengan cara berbeza.'),
      text('Sequence diagrams read top-to-bottom; activity diagrams follow arrows; class and ERD diagrams have no global time direction.', 'Rajah jujukan dibaca dari atas ke bawah; rajah aktiviti mengikut anak panah; rajah kelas dan ERD tidak mempunyai arah masa sejagat.'),
      text('Check the diagram type before deciding where to start.', 'Semak jenis rajah sebelum menentukan titik mula.'),
      text('Left-to-right placement alone does not always mean earlier-to-later.', 'Kedudukan kiri-ke-kanan tidak semestinya bermaksud awal-ke-kemudian.'),
      { aliases: ['top to bottom', 'left to right', 'arah bacaan', 'masa'] }),
    topic('orientation', 'labels-guards', text('Labels and guards', 'Label dan guard'), 'guard',
      text('Labels name a relationship or action; a guard in square brackets states when it is allowed.', 'Label menamakan hubungan atau tindakan; guard dalam kurungan siku menyatakan bila ia dibenarkan.'),
      text('Read `[condition] message` as “send this message only when the condition is true.”', 'Baca `[syarat] mesej` sebagai “hantar mesej ini hanya apabila syarat benar.”'),
      text('Use guards at decisions, transitions and sequence operands.', 'Gunakan guard pada keputusan, peralihan dan operand jujukan.'),
      text('A guard is not a comment and should be testable.', 'Guard bukan komen dan sepatutnya boleh diuji.'),
      { aliases: ['guard', 'condition', 'constraint', 'syarat', 'label'] }),
    topic('orientation', 'boundaries', text('Boundaries and containers', 'Sempadan dan bekas'), 'boundary',
      text('A boundary groups elements that belong to one system, layer, package or responsibility.', 'Sempadan mengumpulkan elemen yang tergolong dalam satu sistem, lapisan, pakej atau tanggungjawab.'),
      text('The boundary gives context; it is usually not a participant receiving messages.', 'Sempadan memberikan konteks; biasanya ia bukan peserta yang menerima mesej.'),
      text('Use boundaries to make scope and ownership explicit.', 'Gunakan sempadan untuk menjelaskan skop dan pemilikan.'),
      text('Do not attach runtime messages to a decorative section container.', 'Jangan sambungkan mesej masa jalan kepada bekas seksyen hiasan.'),
      { aliases: ['boundary', 'container', 'system box', 'sempadan', 'bekas'] }),

    topic('connectors', 'solid-line', text('Solid line', 'Garisan pejal'), 'solid-line',
      text('A solid line commonly represents a direct structural association, control flow or outgoing message.', 'Garisan pejal lazimnya mewakili persatuan struktur, aliran kawalan atau mesej keluar secara langsung.'),
      text('Interpret it together with its arrowhead and diagram family.', 'Tafsirkannya bersama kepala anak panah dan keluarga rajah.'),
      text('Use it for class associations, activity flow and sequence calls.', 'Gunakannya untuk persatuan kelas, aliran aktiviti dan panggilan jujukan.'),
      text('Solid does not universally mean synchronous; inspect the arrowhead too.', 'Pejal tidak semestinya bermaksud segerak; semak kepala anak panah juga.'),
      { aliases: ['solid', 'solid line', 'garisan pejal'], covers: ['association'], explorerRefs: [{ diagramId: 'domain', componentKey: 'user-profile', caption: text('UserProfile associations', 'Persatuan UserProfile') }] }),
    topic('connectors', 'dashed-line', text('Dashed line', 'Garisan putus-putus'), 'dashed-line',
      text('A dashed line usually marks a weaker, logical or response relationship.', 'Garisan putus-putus biasanya menandakan hubungan yang lebih lemah, logik atau respons.'),
      text('Its exact meaning depends on the arrowhead and diagram: dependency, realization, return or logical link.', 'Maksud tepatnya bergantung pada kepala anak panah dan rajah: dependency, realization, return atau pautan logik.'),
      text('Use the label or stereotype to remove ambiguity.', 'Gunakan label atau stereotaip untuk menghapuskan kekaburan.'),
      text('Do not explain a dashed line as “optional” without checking its notation.', 'Jangan terangkan garisan putus-putus sebagai “pilihan” tanpa menyemak notasinya.'),
      { aliases: ['dashed', 'dotted', 'putus-putus', 'garisan putus'], covers: ['logical'] }),
    topic('connectors', 'arrowless-line', text('Line without an arrow', 'Garisan tanpa anak panah'), 'arrowless-line',
      text('An arrowless association says elements are related without claiming a navigation direction.', 'Persatuan tanpa anak panah menyatakan elemen berkaitan tanpa menentukan arah navigasi.'),
      text('Read endpoint labels and multiplicities at both ends.', 'Baca label hujung dan multiplicity pada kedua-dua hujung.'),
      text('Use it when direction is irrelevant or deliberately unspecified.', 'Gunakannya apabila arah tidak relevan atau sengaja tidak ditentukan.'),
      text('It does not mean data flows both ways.', 'Ia tidak bermaksud data mengalir dua hala.'),
      { aliases: ['no arrow', 'association', 'tanpa anak panah'] }),
    topic('connectors', 'open-arrow', text('Open arrowhead', 'Kepala anak panah terbuka'), 'open-arrow',
      text('An open arrowhead points toward a dependency target, return receiver or asynchronous recipient depending on context.', 'Kepala anak panah terbuka menunjuk kepada sasaran dependency, penerima respons atau penerima tak segerak mengikut konteks.'),
      text('Combine line pattern and head shape before naming it.', 'Gabungkan corak garisan dan bentuk kepala sebelum menamakannya.'),
      text('Use it for UML dependencies and dashed sequence returns.', 'Gunakannya untuk dependency UML dan respons jujukan putus-putus.'),
      text('Do not confuse it with a hollow triangular inheritance head.', 'Jangan kelirukannya dengan segi tiga kosong untuk inheritance.'),
      { aliases: ['open arrow', 'open head', 'anak panah terbuka'] }),
    topic('connectors', 'filled-arrow', text('Filled arrowhead', 'Kepala anak panah berisi'), 'filled-arrow',
      text('In these sequence diagrams, a filled classic head represents a synchronous call.', 'Dalam rajah jujukan ini, kepala klasik berisi mewakili panggilan segerak.'),
      text('The sender waits while the receiver performs the call.', 'Penghantar menunggu semasa penerima melaksanakan panggilan.'),
      text('Use it for call messages that transfer control.', 'Gunakannya untuk mesej panggilan yang memindahkan kawalan.'),
      text('Do not use it for a returned result.', 'Jangan gunakannya untuk hasil yang dikembalikan.'),
      { aliases: ['filled arrow', 'solid arrowhead', 'panggilan segerak'], covers: ['sequence-sync'], explorerRefs: [{ diagramId: 'sequence', componentKey: 'participant-manager', caption: text('JobFinderManager calls', 'Panggilan JobFinderManager') }] }),
    topic('connectors', 'triangle-head', text('Hollow triangle', 'Segi tiga kosong'), 'triangle-head',
      text('A hollow triangle points to a more general class or an implemented interface.', 'Segi tiga kosong menunjuk kepada kelas yang lebih umum atau antara muka yang dilaksanakan.'),
      text('Solid line means generalization; dashed line means realization.', 'Garisan pejal bermaksud generalization; garisan putus-putus bermaksud realization.'),
      text('Use it for “is-a” or “implements” relationships.', 'Gunakannya untuk hubungan “ialah sejenis” atau “melaksanakan”.'),
      text('It is not a normal directional arrow.', 'Ia bukan anak panah arah biasa.'),
      { aliases: ['triangle', 'inheritance', 'generalization', 'realization', 'segi tiga', 'pewarisan'] }),
    topic('connectors', 'hollow-diamond', text('Hollow diamond', 'Berlian kosong'), 'hollow-diamond',
      text('A hollow diamond marks shared aggregation: the part can exist independently of the whole.', 'Berlian kosong menandakan aggregation berkongsi: bahagian boleh wujud secara bebas daripada keseluruhan.'),
      text('The diamond is placed at the whole/owner end.', 'Berlian diletakkan pada hujung keseluruhan/pemilik.'),
      text('Use it only when the whole-part meaning adds value.', 'Gunakannya hanya apabila makna keseluruhan-bahagian memberikan nilai.'),
      text('Do not use it merely because one class references another.', 'Jangan gunakannya hanya kerana satu kelas merujuk kelas lain.'),
      { aliases: ['hollow diamond', 'aggregation', 'berlian kosong', 'agregasi'], covers: ['aggregation'], explorerRefs: [{ diagramId: 'domain', componentKey: 'highlight-entity', caption: text('HighlightArea aggregates POI context', 'HighlightArea mengagregat konteks POI') }] }),
    topic('connectors', 'filled-diamond', text('Filled diamond', 'Berlian berisi'), 'filled-diamond',
      text('A filled diamond marks composition: the part belongs exclusively to the whole and shares its lifecycle.', 'Berlian berisi menandakan composition: bahagian dimiliki secara eksklusif dan berkongsi kitar hayat keseluruhan.'),
      text('The diamond is placed at the owning whole.', 'Berlian diletakkan pada keseluruhan yang memiliki.'),
      text('Use it when deleting the whole logically destroys its parts.', 'Gunakannya apabila memadam keseluruhan secara logik memusnahkan bahagiannya.'),
      text('Do not use composition for independently stored services or entities.', 'Jangan gunakan composition untuk servis atau entiti yang disimpan secara bebas.'),
      { aliases: ['filled diamond', 'composition', 'berlian berisi', 'komposisi'], covers: ['composition'], explorerRefs: [{ diagramId: 'implementation', componentKey: 'drawio:class_120', caption: text('MyPetaApp ownership', 'Pemilikan MyPetaApp') }] }),
    topic('connectors', 'crow-foot', text("Crow's-foot end", 'Hujung kaki gagak'), 'crow-foot',
      text("A crow's-foot end means many rows may participate in an ER relationship.", 'Hujung kaki gagak bermaksud banyak baris boleh mengambil bahagian dalam hubungan ER.'),
      text('A circle means zero is allowed; a bar means one is required.', 'Bulatan bermaksud sifar dibenarkan; palang bermaksud satu diperlukan.'),
      text('Use it in ERDs to communicate cardinality compactly.', 'Gunakannya dalam ERD untuk menyampaikan kardinaliti secara padat.'),
      text('Do not mix crow’s-foot marks and UML multiplicity labels on the same connector unless a legend explains it.', 'Jangan campurkan tanda kaki gagak dan label multiplicity UML pada penyambung sama tanpa legenda.'),
      { aliases: ["crow's foot", 'crows foot', 'cardinality', 'kaki gagak', 'kardinaliti'] }),

    topic('usecase', 'actor', text('Actor', 'Aktor'), 'actor',
      text('An actor is an external role that interacts with the system.', 'Aktor ialah peranan luar yang berinteraksi dengan sistem.'),
      text('Read the name as a role, not necessarily one specific person.', 'Baca nama sebagai peranan, bukan semestinya seorang individu tertentu.'),
      text('Place primary actors on the left and supporting or administrative actors on the right when that improves readability.', 'Letakkan aktor utama di kiri dan aktor sokongan atau pentadbiran di kanan apabila membantu kebolehbacaan.'),
      text('Do not model an internal class or database as a human actor.', 'Jangan modelkan kelas dalaman atau pangkalan data sebagai aktor manusia.'),
      { aliases: ['actor', 'stickman', 'user', 'admin', 'aktor', 'orang lidi'], explorerRefs: [{ diagramId: 'usecase', componentKey: 'drawio:actor-user', caption: text('User actor', 'Aktor Pengguna') }] }),
    topic('usecase', 'usecase-ellipse', text('Use case', 'Kes guna'), 'usecase',
      text('A use case names a goal the system provides to an actor.', 'Kes guna menamakan matlamat yang disediakan sistem kepada aktor.'),
      text('Read it as a verb phrase such as “Search jobs.”', 'Bacanya sebagai frasa kata kerja seperti “Cari pekerjaan.”'),
      text('Use it for observable user value, not every button click or private helper method.', 'Gunakannya untuk nilai yang dapat dilihat pengguna, bukan setiap klik butang atau kaedah pembantu peribadi.'),
      text('Do not put implementation classes inside use-case ellipses.', 'Jangan letakkan kelas pelaksanaan dalam elips kes guna.'),
      { aliases: ['use case', 'ellipse', 'pill', 'kes guna', 'bujur'], explorerRefs: [{ diagramId: 'usecase', componentKey: 'drawio:uc-search-jobs', caption: text('Search jobs use case', 'Kes guna Cari pekerjaan') }] }),
    topic('usecase', 'system-boundary', text('System boundary', 'Sempadan sistem'), 'system-boundary',
      text('The rectangle states what belongs to the system being designed.', 'Segi empat menyatakan apa yang tergolong dalam sistem yang direka.'),
      text('Actors stay outside; use cases stay inside.', 'Aktor kekal di luar; kes guna kekal di dalam.'),
      text('Use it to prevent scope ambiguity.', 'Gunakannya untuk mengelakkan kekaburan skop.'),
      text('The boundary is not an actor or message destination.', 'Sempadan bukan aktor atau destinasi mesej.'),
      { aliases: ['system boundary', 'scope', 'sempadan sistem', 'skop'] }),
    topic('usecase', 'actor-association', text('Actor association', 'Persatuan aktor'), 'actor-association',
      text('A solid association links an actor to a use case they participate in.', 'Persatuan pejal menghubungkan aktor kepada kes guna yang disertainya.'),
      text('The line normally has no arrow because participation is the important fact.', 'Garisan biasanya tanpa anak panah kerana penyertaan ialah fakta penting.'),
      text('Use it for direct actor participation.', 'Gunakannya untuk penyertaan langsung aktor.'),
      text('Do not use `include` or `extend` between an actor and a use case.', 'Jangan gunakan `include` atau `extend` antara aktor dan kes guna.'),
      { aliases: ['association', 'actor line', 'garisan aktor'], covers: ['association'] }),
    topic('usecase', 'include', text('«include»', '«include»'), 'include',
      text('The base use case always invokes shared required behaviour.', 'Kes guna asas sentiasa memanggil tingkah laku wajib yang dikongsi.'),
      text('The dashed open arrow points from the base use case to the included use case.', 'Anak panah terbuka putus-putus menunjuk dari kes guna asas kepada kes guna yang disertakan.'),
      text('Use it to reuse mandatory behaviour such as authentication.', 'Gunakannya untuk menggunakan semula tingkah laku wajib seperti pengesahan.'),
      text('Do not use it merely to show what happens next in time.', 'Jangan gunakannya hanya untuk menunjukkan apa yang berlaku seterusnya.'),
      { aliases: ['include', 'mandatory', 'wajib', 'sertakan'], covers: ['include'], explorerRefs: [{ diagramId: 'usecase', componentKey: 'drawio:uc-save-status', caption: text('Save status includes sign-in', 'Simpan status merangkumi log masuk') }] }),
    topic('usecase', 'extend', text('«extend»', '«extend»'), 'extend',
      text('An extension adds conditional or optional behaviour to a complete base use case.', 'Extension menambah tingkah laku bersyarat atau pilihan kepada kes guna asas yang lengkap.'),
      text('The dashed open arrow points from the extending use case toward the base use case.', 'Anak panah terbuka putus-putus menunjuk dari kes guna tambahan kepada kes guna asas.'),
      text('Use it when the base works without the extension.', 'Gunakannya apabila kes guna asas berfungsi tanpa extension.'),
      text('Do not reverse the arrow or use it as a simple sequence arrow.', 'Jangan songsangkan anak panah atau gunakannya sebagai anak panah urutan biasa.'),
      { aliases: ['extend', 'extension', 'optional use case', 'pilihan'], covers: ['extend'], explorerRefs: [{ diagramId: 'usecase', componentKey: 'drawio:uc-job-details', caption: text('View details extends Search jobs', 'Lihat butiran melanjutkan Cari pekerjaan') }] }),
    topic('usecase', 'actor-generalization', text('Actor/use-case generalization', 'Generalisasi aktor/kes guna'), 'triangle-head',
      text('A specialized actor or use case inherits the behaviour of a more general one.', 'Aktor atau kes guna khusus mewarisi tingkah laku yang lebih umum.'),
      text('The hollow triangle points to the general parent.', 'Segi tiga kosong menunjuk kepada induk umum.'),
      text('Use it for a true “is-a” specialization.', 'Gunakannya untuk pengkhususan “ialah sejenis” yang sebenar.'),
      text('Do not use it to mean “calls” or “comes after.”', 'Jangan gunakannya untuk bermaksud “memanggil” atau “selepas”.'),
      { aliases: ['actor inheritance', 'use case generalization', 'generalisasi'] }),

    topic('sequence', 'participant', text('Participant', 'Peserta'), 'participant',
      text('A participant is an actor, object, service or database involved in the interaction.', 'Peserta ialah aktor, objek, servis atau pangkalan data yang terlibat dalam interaksi.'),
      text('Participants are arranged horizontally; time does not run left-to-right.', 'Peserta disusun mendatar; masa tidak bergerak dari kiri ke kanan.'),
      text('Use one lifeline per meaningful runtime role.', 'Gunakan satu lifeline bagi setiap peranan masa jalan yang bermakna.'),
      text('Do not use section containers as participants.', 'Jangan gunakan bekas seksyen sebagai peserta.'),
      { aliases: ['participant', 'object', 'service', 'peserta'], explorerRefs: [{ diagramId: 'sequence', componentKey: 'participant-route', caption: text('Supa Jobs Route participant', 'Peserta Supa Jobs Route') }] }),
    topic('sequence', 'lifeline', text('Lifeline', 'Lifeline'), 'lifeline',
      text('A vertical dashed line represents a participant’s existence through time.', 'Garisan menegak putus-putus mewakili kewujudan peserta mengikut masa.'),
      text('Read downward to move forward in time.', 'Baca ke bawah untuk bergerak ke hadapan dalam masa.'),
      text('Attach messages and activation bars to it.', 'Sambungkan mesej dan bar pengaktifan kepadanya.'),
      text('It is not a data-flow connector.', 'Ia bukan penyambung aliran data.'),
      { aliases: ['lifeline', 'vertical dotted line', 'garisan hayat', 'garisan menegak'] }),
    topic('sequence', 'activation', text('Activation bar', 'Bar pengaktifan'), 'activation',
      text('A narrow rectangle shows when a participant is executing or controlling work.', 'Segi empat sempit menunjukkan bila peserta sedang melaksanakan atau mengawal kerja.'),
      text('It usually begins on receipt of a call and ends after the response or work completes.', 'Ia biasanya bermula apabila menerima panggilan dan berakhir selepas respons atau kerja selesai.'),
      text('Use it to make nested processing visible.', 'Gunakannya untuk menunjukkan pemprosesan bersarang.'),
      text('Do not extend every activation to the bottom without reason.', 'Jangan panjangkan setiap pengaktifan ke bawah tanpa sebab.'),
      { aliases: ['activation', 'execution specification', 'bar biru', 'pengaktifan'] }),
    topic('sequence', 'sync-call', text('Synchronous call', 'Panggilan segerak'), 'sync-call',
      text('A solid line with a filled head transfers control and the sender waits.', 'Garisan pejal berkepala berisi memindahkan kawalan dan penghantar menunggu.'),
      text('Read it as a function or request call.', 'Bacanya sebagai panggilan fungsi atau permintaan.'),
      text('Use it for ordinary method calls and awaited HTTP requests.', 'Gunakannya untuk panggilan kaedah biasa dan permintaan HTTP yang ditunggu.'),
      text('Do not use it for a returned value.', 'Jangan gunakannya untuk nilai yang dikembalikan.'),
      { aliases: ['synchronous', 'sync call', 'solid call', 'panggilan segerak'], covers: ['sequence-sync'] }),
    topic('sequence', 'async-call', text('Asynchronous message', 'Mesej tak segerak'), 'async-call',
      text('A solid message with an open head does not require the sender to wait for completion.', 'Mesej pejal berkepala terbuka tidak memerlukan penghantar menunggu sehingga selesai.'),
      text('Read it as “send and continue.”', 'Bacanya sebagai “hantar dan teruskan.”'),
      text('Use it for events, queues and notifications.', 'Gunakannya untuk peristiwa, baris gilir dan notifikasi.'),
      text('Do not mark awaited calls as asynchronous merely because JavaScript uses promises.', 'Jangan tandakan panggilan yang ditunggu sebagai tak segerak hanya kerana JavaScript menggunakan promise.'),
      { aliases: ['asynchronous', 'async message', 'event', 'tak segerak'] }),
    topic('sequence', 'return-message', text('Return message', 'Mesej pulangan'), 'return-message',
      text('A dashed line with an open head optionally shows a returned value or control.', 'Garisan putus-putus berkepala terbuka secara pilihan menunjukkan nilai atau kawalan yang dikembalikan.'),
      text('It points back to the caller.', 'Ia menunjuk kembali kepada pemanggil.'),
      text('Use it when the returned data matters to understanding the scenario.', 'Gunakannya apabila data pulangan penting untuk memahami senario.'),
      text('Do not draw every trivial return if it makes the diagram noisy.', 'Jangan lukis setiap pulangan remeh jika ia menjadikan rajah berserabut.'),
      { aliases: ['return', 'response', 'dashed response', 'pulangan', 'respons'], covers: ['sequence-return'], explorerRefs: [{ diagramId: 'sequence', componentKey: 'participant-client', caption: text('JobGrepResponse return path', 'Laluan pulangan JobGrepResponse') }] }),
    topic('sequence', 'self-message', text('Self-message (“U-turn”)', 'Mesej kendiri (“pusingan U”)'), 'self-message',
      text('A participant calls one of its own operations, so the arrow leaves and returns to the same lifeline.', 'Peserta memanggil operasinya sendiri, jadi anak panah keluar dan kembali kepada lifeline yang sama.'),
      text('Read it as an internal method call or recursion.', 'Bacanya sebagai panggilan kaedah dalaman atau rekursi.'),
      text('Use it only for a real self-call such as `applyClientFilters()`.', 'Gunakannya hanya untuk panggilan kendiri sebenar seperti `applyClientFilters()`.'),
      text('“Catch fetch failure” is control flow, not a self-message; represent it with an `alt` operand.', '“Catch fetch failure” ialah aliran kawalan, bukan mesej kendiri; wakilkannya dengan operand `alt`.'),
      { aliases: ['self message', 'self call', 'self-call', 'u-turn', 'uturn', 'recursion', 'mesej kendiri', 'pusingan u'], covers: ['sequence-self'], explorerRefs: [{ diagramId: 'sequence', componentKey: 'participant-manager', caption: text('JobFinderManager self-calls', 'Panggilan kendiri JobFinderManager') }] }),
    topic('sequence', 'create-destroy', text('Creation and destruction', 'Penciptaan dan pemusnahan'), 'create-destroy',
      text('A creation message starts a new lifeline; an X terminates one.', 'Mesej penciptaan memulakan lifeline baharu; tanda X menamatkannya.'),
      text('The created participant begins at the creation message rather than the top.', 'Peserta yang dicipta bermula pada mesej penciptaan, bukan dari bahagian atas.'),
      text('Use it when object lifetime is important.', 'Gunakannya apabila jangka hayat objek penting.'),
      text('Do not use destruction to mean an HTTP error.', 'Jangan gunakan pemusnahan untuk bermaksud ralat HTTP.'),
      { aliases: ['create message', 'destroy', 'destruction x', 'penciptaan', 'pemusnahan'] }),
    topic('sequence', 'sequence-guard', text('Sequence guard', 'Guard jujukan'), 'guard',
      text('A guard is a Boolean condition controlling a message or operand.', 'Guard ialah syarat Boolean yang mengawal mesej atau operand.'),
      text('Read `[session exists]` as the condition required for that path.', 'Baca `[session exists]` sebagai syarat yang diperlukan bagi laluan tersebut.'),
      text('Use mutually clear guards inside `alt` fragments.', 'Gunakan guard yang jelas dan saling membezakan dalam fragmen `alt`.'),
      text('Avoid vague guards such as `[okay]` when a testable condition is available.', 'Elakkan guard kabur seperti `[okay]` apabila syarat boleh diuji tersedia.'),
      { aliases: ['sequence guard', 'condition', 'syarat jujukan'] }),

    topic('fragments', 'alt-fragment', text('alt — alternatives', 'alt — alternatif'), 'fragment-alt',
      text('An `alt` fragment contains two or more guarded alternatives; exactly one valid operand runs.', 'Fragmen `alt` mengandungi dua atau lebih alternatif ber-guard; tepat satu operand yang sah dilaksanakan.'),
      text('Evaluate guards from the scenario and follow the matching compartment.', 'Nilai guard berdasarkan senario dan ikuti petak yang sepadan.'),
      text('Use it for success/failure, found/not-found or role-based branches.', 'Gunakannya untuk cabang berjaya/gagal, dijumpai/tidak dijumpai atau berdasarkan peranan.'),
      text('Do not use separate self-messages merely to say an exception was caught.', 'Jangan gunakan mesej kendiri berasingan hanya untuk menyatakan pengecualian ditangkap.'),
      { aliases: ['alt', 'alternative', 'else', 'alternatif'], explorerRefs: [{ diagramId: 'sequence', componentKey: 'fragment-results', caption: text('Job result alternatives', 'Alternatif hasil pekerjaan') }] }),
    topic('fragments', 'opt-fragment', text('opt — optional path', 'opt — laluan pilihan'), 'fragment-opt',
      text('An `opt` fragment contains one guarded sequence that may execute once or be skipped.', 'Fragmen `opt` mengandungi satu jujukan ber-guard yang mungkin dilaksanakan sekali atau dilangkau.'),
      text('If the guard is false, continue below the frame.', 'Jika guard palsu, teruskan di bawah bingkai.'),
      text('Use it for optional enrichment or UI updates.', 'Gunakannya untuk pengayaan atau kemas kini UI pilihan.'),
      text('Use `alt`, not `opt`, when an explicit else path must be shown.', 'Gunakan `alt`, bukan `opt`, apabila laluan else perlu ditunjukkan.'),
      { aliases: ['opt', 'optional', 'if', 'pilihan', 'opsyenal'] }),
    topic('fragments', 'loop-fragment', text('loop — repetition', 'loop — pengulangan'), 'fragment-loop',
      text('A `loop` fragment repeats its operand while its guard or bounds allow it.', 'Fragmen `loop` mengulangi operand selagi guard atau had membenarkannya.'),
      text('Read the guard or range before following the repeated messages.', 'Baca guard atau julat sebelum mengikuti mesej yang berulang.'),
      text('Use it for retries, pages or collections.', 'Gunakannya untuk percubaan semula, halaman atau koleksi.'),
      text('Do not use a loop when only one conditional execution is possible.', 'Jangan gunakan loop apabila hanya satu pelaksanaan bersyarat mungkin.'),
      { aliases: ['loop', 'repeat', 'retry', 'gelung', 'ulang'] }),
    topic('fragments', 'par-fragment', text('par — parallel work', 'par — kerja selari'), 'fragment-par',
      text('A `par` fragment contains operands that may execute concurrently.', 'Fragmen `par` mengandungi operand yang boleh dilaksanakan serentak.'),
      text('Each compartment is an independent concurrent trace.', 'Setiap petak ialah jejak serentak yang bebas.'),
      text('Use it when ordering between branches is intentionally unconstrained.', 'Gunakannya apabila urutan antara cabang sengaja tidak ditetapkan.'),
      text('Do not use it for ordinary sequential calls that merely use async syntax.', 'Jangan gunakannya untuk panggilan berurutan biasa yang hanya menggunakan sintaks async.'),
      { aliases: ['par', 'parallel', 'concurrent', 'selari', 'serentak'] }),
    topic('fragments', 'break-fragment', text('break — stop the enclosing flow', 'break — hentikan aliran'), 'fragment-break',
      text('A `break` fragment executes under its guard and abandons the remainder of the enclosing interaction.', 'Fragmen `break` dilaksanakan apabila guard benar dan meninggalkan baki interaksi luar.'),
      text('After the break operand, do not continue with later messages in that scenario.', 'Selepas operand break, jangan teruskan mesej berikutnya dalam senario tersebut.'),
      text('Use it for unrecoverable validation or cancellation.', 'Gunakannya untuk pengesahan gagal yang tidak boleh dipulihkan atau pembatalan.'),
      text('Do not use it for a normal return that allows the scenario to continue.', 'Jangan gunakannya untuk pulangan biasa yang membenarkan senario diteruskan.'),
      { aliases: ['break', 'abort', 'stop flow', 'henti', 'batal'] }),
    topic('fragments', 'ref-fragment', text('ref — referenced interaction', 'ref — interaksi rujukan'), 'fragment-ref',
      text('A `ref` fragment points to a reusable interaction described elsewhere.', 'Fragmen `ref` menunjuk kepada interaksi boleh guna semula yang diterangkan di tempat lain.'),
      text('Read the reference name, then open the linked sequence if detail is required.', 'Baca nama rujukan, kemudian buka jujukan berkaitan jika butiran diperlukan.'),
      text('Use it to keep large sequences readable.', 'Gunakannya untuk memastikan jujukan besar mudah dibaca.'),
      text('Do not hide critical logic behind an undefined reference.', 'Jangan sembunyikan logik kritikal di sebalik rujukan yang tidak ditakrifkan.'),
      { aliases: ['ref', 'reference', 'interaction use', 'rujukan'] }),
    topic('fragments', 'operand-divider', text('Operand divider', 'Pembahagi operand'), 'operand-divider',
      text('A horizontal dashed divider separates alternatives or parallel operands inside a fragment.', 'Pembahagi mendatar putus-putus memisahkan alternatif atau operand selari dalam fragmen.'),
      text('Read the guard near the top of each compartment.', 'Baca guard berhampiran bahagian atas setiap petak.'),
      text('Use it only inside a multi-operand combined fragment.', 'Gunakannya hanya dalam fragmen gabungan berbilang operand.'),
      text('It is not a return message because it does not connect lifelines.', 'Ia bukan mesej pulangan kerana tidak menghubungkan lifeline.'),
      { aliases: ['operand', 'divider', 'dashed divider', 'pembahagi operand'] }),

    topic('activity', 'flowchart-basics', text('Flow Chart basics', 'Asas Carta Alir'), 'flowchart-basics',
      text('A flow chart uses a terminator for Start/End, rectangles for processes and diamonds for decisions.', 'Carta alir menggunakan terminator untuk Mula/Tamat, segi empat untuk proses dan berlian untuk keputusan.'),
      text('Begin at Start, follow each arrow, and choose the explicitly labelled Yes or No branch at every decision.', 'Bermula pada Mula, ikuti setiap anak panah dan pilih cabang Ya atau Tidak yang dilabel dengan jelas pada setiap keputusan.'),
      text('Use it to explain one procedural path and its success or failure outcomes in report-friendly language.', 'Gunakannya untuk menerangkan satu laluan prosedur serta hasil berjaya atau gagal dengan bahasa yang sesuai untuk laporan.'),
      text('Do not omit branch labels, leave a path disconnected, or use a process rectangle for a question.', 'Jangan tinggalkan label cabang, biarkan laluan terputus atau gunakan segi empat proses untuk soalan.'),
      { aliases: ['flow chart', 'flowchart', 'terminator', 'process', 'decision', 'yes no', 'carta alir', 'mula tamat', 'proses', 'keputusan'], covers: ['flow', 'flow-decision'], explorerRefs: [{ diagramId: 'user-google-sign-in-flowchart', componentKey: 'authorization-completed', caption: text('Google authorization decision', 'Keputusan pengesahan Google') }] }),
    topic('activity', 'initial-final', text('Initial and final nodes', 'Nod awal dan akhir'), 'activity-start-end',
      text('A filled circle starts the activity; a bullseye ends the full activity.', 'Bulatan berisi memulakan aktiviti; bulatan sasaran menamatkan keseluruhan aktiviti.'),
      text('Begin at the initial node and follow outgoing control flow.', 'Bermula pada nod awal dan ikuti aliran kawalan keluar.'),
      text('Use one clear initial node per activity region.', 'Gunakan satu nod awal yang jelas bagi setiap rantau aktiviti.'),
      text('Do not confuse activity final with flow final.', 'Jangan kelirukan activity final dengan flow final.'),
      { aliases: ['initial', 'final', 'start', 'end', 'mula', 'akhir'] }),
    topic('activity', 'action', text('Action', 'Tindakan'), 'activity-action',
      text('A rounded rectangle represents one executable step.', 'Segi empat bucu bulat mewakili satu langkah boleh laksana.'),
      text('Read actions as verb phrases and follow the arrows between them.', 'Baca tindakan sebagai frasa kata kerja dan ikuti anak panah antaranya.'),
      text('Use it for a meaningful unit of work.', 'Gunakannya untuk unit kerja yang bermakna.'),
      text('Do not place a decision question inside an action when a decision node is clearer.', 'Jangan letakkan soalan keputusan dalam tindakan apabila nod keputusan lebih jelas.'),
      { aliases: ['action', 'activity', 'rounded rectangle', 'tindakan', 'aktiviti'] }),
    topic('activity', 'decision-merge', text('Decision and merge', 'Keputusan dan gabung'), 'activity-decision',
      text('A diamond with one input and guarded outputs is a decision; multiple inputs and one output form a merge.', 'Berlian dengan satu input dan output ber-guard ialah keputusan; beberapa input dan satu output ialah gabung.'),
      text('Follow only the outgoing edge whose guard is true.', 'Ikuti hanya sisi keluar yang guardnya benar.'),
      text('Use decisions for mutually exclusive paths.', 'Gunakan keputusan untuk laluan yang saling eksklusif.'),
      text('Do not use a decision diamond to run branches in parallel.', 'Jangan gunakan berlian keputusan untuk menjalankan cabang secara selari.'),
      { aliases: ['decision', 'merge', 'diamond', 'keputusan', 'gabung'] }),
    topic('activity', 'fork-join', text('Fork and join', 'Fork dan join'), 'activity-fork',
      text('A thick bar splits work into concurrent branches or waits for branches to join.', 'Bar tebal memisahkan kerja kepada cabang serentak atau menunggu cabang bergabung.'),
      text('A fork has one input and many outputs; a join has many inputs and one output.', 'Fork mempunyai satu input dan banyak output; join mempunyai banyak input dan satu output.'),
      text('Use it when branches genuinely execute independently.', 'Gunakannya apabila cabang benar-benar dilaksanakan secara bebas.'),
      text('Do not substitute it for a decision where only one path runs.', 'Jangan gantikannya dengan keputusan apabila hanya satu laluan dilaksanakan.'),
      { aliases: ['fork', 'join', 'synchronization bar', 'parallel', 'selari'] }),
    topic('activity', 'swimlane', text('Swimlane', 'Swimlane'), 'activity-swimlane',
      text('A swimlane groups actions by responsible actor, team or component.', 'Swimlane mengumpulkan tindakan mengikut aktor, pasukan atau komponen yang bertanggungjawab.'),
      text('Follow control flow across lane boundaries while noting who owns each action.', 'Ikuti aliran kawalan merentasi sempadan lorong sambil melihat pemilik setiap tindakan.'),
      text('Use it when responsibility hand-offs matter.', 'Gunakannya apabila pertukaran tanggungjawab penting.'),
      text('Do not use lanes only as decorative columns.', 'Jangan gunakan lorong hanya sebagai lajur hiasan.'),
      { aliases: ['swimlane', 'partition', 'responsibility', 'lorong', 'tanggungjawab'] }),
    topic('activity', 'object-flow', text('Control flow vs object flow', 'Aliran kawalan lwn objek'), 'activity-object-flow',
      text('Control flow carries execution; object flow carries data or an object token between actions.', 'Aliran kawalan membawa pelaksanaan; aliran objek membawa data atau token objek antara tindakan.'),
      text('Read object nodes and labels to identify the transferred data.', 'Baca nod objek dan label untuk mengenal pasti data yang dipindahkan.'),
      text('Use object flow when the data itself matters to the process.', 'Gunakan aliran objek apabila data itu sendiri penting kepada proses.'),
      text('Do not label every control arrow with a database table name and call it object flow.', 'Jangan labelkan setiap anak panah kawalan dengan nama jadual dan memanggilnya aliran objek.'),
      { aliases: ['control flow', 'object flow', 'data token', 'aliran kawalan', 'aliran objek'] }),

    topic('class', 'class-compartments', text('Class and compartments', 'Kelas dan petak'), 'class-box',
      text('A class box typically separates its name, attributes and operations.', 'Kotak kelas biasanya memisahkan nama, atribut dan operasi.'),
      text('Read the class name first, then its stored data and provided behaviour.', 'Baca nama kelas dahulu, kemudian data yang disimpan dan tingkah laku yang disediakan.'),
      text('Use compartments when implementation detail helps the reader.', 'Gunakan petak apabila butiran pelaksanaan membantu pembaca.'),
      text('Do not attach relationships to an attribute row instead of the outer class.', 'Jangan sambungkan hubungan kepada baris atribut dan bukannya kelas luar.'),
      { aliases: ['class', 'compartment', 'attribute', 'operation', 'kelas', 'petak'], explorerRefs: [{ diagramId: 'domain', componentKey: 'user-profile', caption: text('UserProfile class', 'Kelas UserProfile') }] }),
    topic('class', 'visibility-types', text('Visibility, types and scope', 'Keterlihatan, jenis dan skop'), 'class-visibility',
      text('`+` public, `-` private, `#` protected and `~` package; a colon introduces a type.', '`+` public, `-` private, `#` protected dan `~` package; titik bertindih memperkenalkan jenis.'),
      text('Underlined members are static/class scoped; italic names usually indicate abstraction.', 'Ahli bergaris bawah ialah static/skop kelas; nama condong biasanya menunjukkan abstraksi.'),
      text('Use these markers when the design needs code-level precision.', 'Gunakan penanda ini apabila reka bentuk memerlukan ketepatan tahap kod.'),
      text('Do not invent visibility for conceptual database entities without evidence.', 'Jangan reka keterlihatan bagi entiti pangkalan data konseptual tanpa bukti.'),
      { aliases: ['public', 'private', 'protected', 'static', 'abstract', 'visibility', 'keterlihatan'] }),
    topic('class', 'stereotype', text('Stereotype', 'Stereotaip'), 'stereotype',
      text('A stereotype such as `«entity»` or `«service»` adds a defined modeling role.', 'Stereotaip seperti `«entity»` atau `«service»` menambah peranan pemodelan yang ditakrifkan.'),
      text('Read it as classification metadata, not part of the class name.', 'Bacanya sebagai metadata pengelasan, bukan sebahagian nama kelas.'),
      text('Use it consistently and explain custom stereotypes in a legend.', 'Gunakannya secara konsisten dan terangkan stereotaip tersuai dalam legenda.'),
      text('Do not call a Supabase table an ORM class merely by adding `«entity»`.', 'Jangan panggil jadual Supabase sebagai kelas ORM hanya dengan menambah `«entity»`.'),
      { aliases: ['stereotype', 'entity', 'service', 'interface', 'stereotaip'] }),
    topic('class', 'multiplicity', text('Multiplicity', 'Multiplicity'), 'multiplicity',
      text('Multiplicity states how many instances may participate at an association end.', 'Multiplicity menyatakan bilangan instance yang boleh mengambil bahagian pada hujung persatuan.'),
      text('Read `1`, `0..1`, `0..*` and `1..*` at the class they describe.', 'Baca `1`, `0..1`, `0..*` dan `1..*` pada kelas yang diterangkannya.'),
      text('Use it when cardinality affects the domain rules.', 'Gunakannya apabila kardinaliti mempengaruhi peraturan domain.'),
      text('Do not place both endpoint labels beside the same class.', 'Jangan letakkan kedua-dua label hujung di sebelah kelas yang sama.'),
      { aliases: ['multiplicity', 'cardinality', '0..1', '0..*', '1..*', 'kepelbagaian', 'kardinaliti'] }),
    topic('class', 'navigability', text('Association and navigability', 'Persatuan dan navigasi'), 'navigability',
      text('A solid association records a structural link; an optional arrow shows which class knows or can navigate to the other.', 'Persatuan pejal merekodkan pautan struktur; anak panah pilihan menunjukkan kelas yang mengetahui atau boleh menavigasi ke kelas lain.'),
      text('Read a navigability arrow independently from multiplicity.', 'Baca anak panah navigasi secara berasingan daripada multiplicity.'),
      text('Use it when direction of knowledge matters.', 'Gunakannya apabila arah pengetahuan penting.'),
      text('Do not treat navigability as runtime message order.', 'Jangan anggap navigasi sebagai urutan mesej masa jalan.'),
      { aliases: ['association', 'navigability', 'navigation', 'persatuan', 'navigasi'], covers: ['association'] }),
    topic('class', 'dependency', text('Dependency', 'Dependency'), 'dependency',
      text('A dashed open arrow means the source depends on the target’s definition or service.', 'Anak panah terbuka putus-putus bermaksud sumber bergantung pada definisi atau servis sasaran.'),
      text('The arrow points toward the supplier being depended on.', 'Anak panah menunjuk kepada pembekal yang digunakan.'),
      text('Use it for imports, parameter types or service calls that are not ownership.', 'Gunakannya untuk import, jenis parameter atau panggilan servis yang bukan pemilikan.'),
      text('Do not use a dependency when a persistent domain association is intended.', 'Jangan gunakan dependency apabila persatuan domain kekal dimaksudkan.'),
      { aliases: ['dependency', 'depends on', 'uses', 'kebergantungan', 'bergantung'], covers: ['dependency'], explorerRefs: [{ diagramId: 'implementation', componentKey: 'drawio:class_120', caption: text('Implementation dependencies', 'Dependency pelaksanaan') }] }),
    topic('class', 'realization', text('Realization', 'Realization'), 'realization',
      text('A dashed line with a hollow triangle says a class implements an interface or contract.', 'Garisan putus-putus dengan segi tiga kosong menyatakan kelas melaksanakan antara muka atau kontrak.'),
      text('The triangle points to the interface or specification.', 'Segi tiga menunjuk kepada antara muka atau spesifikasi.'),
      text('Use it for explicit implementation contracts.', 'Gunakannya untuk kontrak pelaksanaan eksplisit.'),
      text('Do not use it for a simple module import.', 'Jangan gunakannya untuk import modul biasa.'),
      { aliases: ['realization', 'implements', 'interface implementation', 'melaksanakan'] }),
    topic('class', 'generalization', text('Generalization / inheritance', 'Generalisasi / inheritance'), 'generalization',
      text('A solid line with a hollow triangle models an “is-a” specialization.', 'Garisan pejal dengan segi tiga kosong memodelkan pengkhususan “ialah sejenis”.'),
      text('The triangle points to the general parent class.', 'Segi tiga menunjuk kepada kelas induk umum.'),
      text('Use it when the subtype can substitute for the parent.', 'Gunakannya apabila subjenis boleh menggantikan induk.'),
      text('Do not create inheritance merely to share a few fields.', 'Jangan cipta inheritance hanya untuk berkongsi beberapa medan.'),
      { aliases: ['generalization', 'inheritance', 'is-a', 'pewarisan', 'generalisasi'] }),
    topic('class', 'aggregation', text('Aggregation', 'Aggregation'), 'hollow-diamond',
      text('Shared whole-part relationship where the part has an independent lifecycle.', 'Hubungan keseluruhan-bahagian berkongsi di mana bahagian mempunyai kitar hayat bebas.'),
      text('The hollow diamond is at the whole.', 'Berlian kosong berada pada keseluruhan.'),
      text('Use it sparingly when shared ownership is a real domain rule.', 'Gunakannya secara terhad apabila pemilikan berkongsi ialah peraturan domain sebenar.'),
      text('A collection property alone does not automatically justify aggregation.', 'Sifat koleksi sahaja tidak secara automatik mewajarkan aggregation.'),
      { aliases: ['aggregation', 'shared part', 'agregasi'], covers: ['aggregation'] }),
    topic('class', 'composition', text('Composition', 'Composition'), 'filled-diamond',
      text('Strong whole-part ownership where the part cannot meaningfully outlive the whole.', 'Pemilikan keseluruhan-bahagian yang kuat di mana bahagian tidak boleh kekal selepas keseluruhan.'),
      text('The filled diamond is at the owner.', 'Berlian berisi berada pada pemilik.'),
      text('Use it for owned manager/component lifecycles.', 'Gunakannya untuk kitar hayat manager/komponen yang dimiliki.'),
      text('Do not use it for independently persisted rows.', 'Jangan gunakannya untuk baris yang disimpan secara bebas.'),
      { aliases: ['composition', 'ownership', 'komposisi', 'pemilikan'], covers: ['composition'] }),

    topic('erd', 'entity-table', text('Entity / table', 'Entiti / jadual'), 'erd-entity',
      text('An ERD entity represents a table-like set of records with named columns.', 'Entiti ERD mewakili set rekod seperti jadual dengan lajur bernama.'),
      text('Read the entity name, key fields and relationship endpoints.', 'Baca nama entiti, medan kekunci dan hujung hubungan.'),
      text('Use it to model persistent data structure.', 'Gunakannya untuk memodelkan struktur data kekal.'),
      text('Do not assume an ERD entity exposes application methods.', 'Jangan anggap entiti ERD mendedahkan kaedah aplikasi.'),
      { aliases: ['entity', 'table', 'record', 'entiti', 'jadual'], explorerRefs: [{ diagramId: 'supabase', componentKey: 'table:users', caption: text('public.users table', 'Jadual public.users') }] }),
    topic('erd', 'database-keys', text('PK, FK and UQ', 'PK, FK dan UQ'), 'erd-keys',
      text('PK identifies a row, FK references another table, and UQ prevents duplicate values.', 'PK mengenal pasti baris, FK merujuk jadual lain, dan UQ menghalang nilai pendua.'),
      text('Trace each FK from its source column to the referenced key.', 'Jejaki setiap FK dari lajur sumber kepada kekunci yang dirujuk.'),
      text('Use key markers to explain identity and integrity.', 'Gunakan penanda kekunci untuk menerangkan identiti dan integriti.'),
      text('A logical application link is not automatically a database FK.', 'Pautan logik aplikasi bukan secara automatik FK pangkalan data.'),
      { aliases: ['pk', 'primary key', 'fk', 'foreign key', 'unique', 'kekunci utama', 'kekunci asing'] }),
    topic('erd', 'nullability', text('Nullability and optionality', 'Nullability dan opsyenaliti'), 'erd-nullable',
      text('A nullable foreign key allows a row to exist without the related row.', 'Foreign key nullable membenarkan baris wujud tanpa baris berkaitan.'),
      text('This often produces a `0..1` relationship at the referenced end.', 'Ini lazimnya menghasilkan hubungan `0..1` pada hujung yang dirujuk.'),
      text('Use schema nullability when deriving minimum cardinality.', 'Gunakan nullability skema apabila memperoleh kardinaliti minimum.'),
      text('Do not infer optionality from screen layout alone.', 'Jangan simpulkan opsyenaliti daripada susun atur skrin sahaja.'),
      { aliases: ['nullable', 'optional', 'null', 'opsyenal', 'boleh kosong'] }),
    topic('erd', 'erd-cardinality', text('ER cardinality', 'Kardinaliti ER'), 'crow-foot',
      text('Endpoint marks describe minimum and maximum related rows.', 'Tanda hujung menerangkan bilangan minimum dan maksimum baris berkaitan.'),
      text('Read both ends to form a complete sentence, such as one state has zero or many POIs.', 'Baca kedua-dua hujung untuk membentuk ayat lengkap, seperti satu negeri mempunyai sifar atau banyak POI.'),
      text('Use schema constraints as the source of truth.', 'Gunakan kekangan skema sebagai sumber kebenaran.'),
      text('Do not swap the cardinalities because of visual left/right placement.', 'Jangan tukar kardinaliti kerana kedudukan kiri/kanan visual.'),
      { aliases: ['one to many', 'many to many', '1:m', 'm:n', 'satu ke banyak', 'kardinaliti'] }),
    topic('erd', 'bridge-table', text('Bridge / junction table', 'Jadual penghubung'), 'erd-bridge',
      text('A bridge table resolves a many-to-many relationship into two one-to-many relationships.', 'Jadual penghubung menyelesaikan hubungan banyak-ke-banyak kepada dua hubungan satu-ke-banyak.'),
      text('Its key commonly combines the foreign keys or adds a surrogate ID plus a unique constraint.', 'Kekuncinya lazimnya menggabungkan foreign key atau menambah ID surrogate bersama kekangan unik.'),
      text('Use it when the relationship itself stores attributes.', 'Gunakannya apabila hubungan itu sendiri menyimpan atribut.'),
      text('Do not draw a direct many-to-many link if the real schema uses a junction table and that detail matters.', 'Jangan lukis pautan banyak-ke-banyak terus jika skema sebenar menggunakan jadual penghubung dan butiran itu penting.'),
      { aliases: ['bridge table', 'junction table', 'join table', 'jadual penghubung'] }),
    topic('erd', 'fk-logical', text('Foreign key vs logical link', 'Foreign key lwn pautan logik'), 'erd-logical',
      text('A database FK is enforced by PostgreSQL; a logical link is resolved by application conventions.', 'FK pangkalan data dikuatkuasakan PostgreSQL; pautan logik diselesaikan melalui konvensyen aplikasi.'),
      text('Use a solid FK relationship and a clearly labeled dashed logical link.', 'Gunakan hubungan FK pejal dan pautan logik putus-putus yang dilabel jelas.'),
      text('Use logical links only when the schema lacks a formal constraint.', 'Gunakan pautan logik hanya apabila skema tidak mempunyai kekangan formal.'),
      text('Do not report a logical bridge as a live FK.', 'Jangan laporkan bridge logik sebagai FK sebenar.'),
      { aliases: ['logical link', 'foreign key', 'better auth bridge', 'pautan logik'], covers: ['logical'], explorerRefs: [{ diagramId: 'domain', componentKey: 'auth-identity', caption: text('Better Auth logical profile bridge', 'Bridge profil logik Better Auth') }] }),

    topic('architecture', 'architecture-elements', text('Component, module and service', 'Komponen, modul dan servis'), 'architecture-elements',
      text('These boxes describe implementation responsibilities at different boundaries.', 'Kotak ini menerangkan tanggungjawab pelaksanaan pada sempadan berbeza.'),
      text('Read labels and stereotypes before assuming deployment or ownership.', 'Baca label dan stereotaip sebelum menganggap deployment atau pemilikan.'),
      text('Use consistent shapes or stereotypes and provide a legend.', 'Gunakan bentuk atau stereotaip yang konsisten dan sediakan legenda.'),
      text('Do not mix class-level and deployment-level meaning without explanation.', 'Jangan campurkan makna tahap kelas dan deployment tanpa penerangan.'),
      { aliases: ['component', 'module', 'service', 'komponen', 'modul', 'servis'] }),
    topic('architecture', 'database-external', text('Database and external system', 'Pangkalan data dan sistem luar'), 'architecture-database',
      text('A cylinder commonly indicates storage; an external box represents a dependency outside the system boundary.', 'Silinder lazimnya menunjukkan storan; kotak luar mewakili dependency di luar sempadan sistem.'),
      text('Check the boundary to determine ownership.', 'Semak sempadan untuk menentukan pemilikan.'),
      text('Use explicit labels such as Supabase or Google OAuth.', 'Gunakan label eksplisit seperti Supabase atau Google OAuth.'),
      text('Do not imply the application controls an external provider.', 'Jangan gambarkan seolah-olah aplikasi mengawal penyedia luar.'),
      { aliases: ['database', 'external system', 'cylinder', 'pangkalan data', 'sistem luar'] }),
    topic('architecture', 'containment-layers', text('Containment and layers', 'Bekas dan lapisan'), 'architecture-layers',
      text('Containers group elements by deployment, responsibility or architectural layer.', 'Bekas mengumpulkan elemen mengikut deployment, tanggungjawab atau lapisan seni bina.'),
      text('Read layer boundaries separately from runtime connectors.', 'Baca sempadan lapisan secara berasingan daripada penyambung masa jalan.'),
      text('Use layers to show allowed dependency direction.', 'Gunakan lapisan untuk menunjukkan arah dependency yang dibenarkan.'),
      text('Do not treat visual containment as UML composition unless explicitly marked.', 'Jangan anggap bekas visual sebagai composition UML melainkan ditandakan.'),
      { aliases: ['layer', 'containment', 'package', 'lapisan', 'bekas'] }),
    topic('architecture', 'ownership-dependency', text('Ownership vs dependency', 'Pemilikan lwn dependency'), 'ownership-dependency',
      text('Ownership controls lifecycle; dependency only means one element uses another.', 'Pemilikan mengawal kitar hayat; dependency hanya bermaksud satu elemen menggunakan elemen lain.'),
      text('Use composition for owned managers and dashed dependency for imported services.', 'Gunakan composition untuk manager yang dimiliki dan dependency putus-putus untuk servis yang diimport.'),
      text('Use the weaker relationship unless lifecycle ownership is known.', 'Gunakan hubungan yang lebih lemah melainkan pemilikan kitar hayat diketahui.'),
      text('Do not replace every architecture arrow with composition.', 'Jangan gantikan setiap anak panah seni bina dengan composition.'),
      { aliases: ['ownership', 'dependency', 'composition', 'pemilikan', 'kebergantungan'], covers: ['dependency', 'composition'] }),
    topic('architecture', 'directed-data-flow', text('Directed data flow', 'Aliran data berarah'), 'data-flow',
      text('A directed flow arrow shows information moving from source to consumer.', 'Anak panah aliran berarah menunjukkan maklumat bergerak dari sumber kepada pengguna.'),
      text('Read the label as the payload, protocol or transformation.', 'Baca label sebagai payload, protokol atau transformasi.'),
      text('Use it for request, response, ingest and render paths.', 'Gunakannya untuk laluan permintaan, respons, ingestion dan paparan.'),
      text('A data-flow arrow does not by itself prove a persistent structural association.', 'Anak panah aliran data tidak dengan sendirinya membuktikan persatuan struktur kekal.'),
      { aliases: ['data flow', 'request flow', 'pipeline', 'aliran data', 'laluan permintaan'] }),

    topic('state', 'state', text('State', 'Keadaan'), 'state',
      text('A rounded rectangle names a stable condition of one object or system.', 'Segi empat bucu bulat menamakan keadaan stabil bagi satu objek atau sistem.'),
      text('Read it as “the object is currently in this condition.”', 'Bacanya sebagai “objek kini berada dalam keadaan ini.”'),
      text('Use states that change permitted behaviour.', 'Gunakan keadaan yang mengubah tingkah laku yang dibenarkan.'),
      text('Do not use an action verb when an activity node is intended.', 'Jangan gunakan kata kerja tindakan apabila nod aktiviti dimaksudkan.'),
      { aliases: ['state', 'status', 'keadaan', 'status'] }),
    topic('state', 'state-initial-final', text('Initial and final state', 'Keadaan awal dan akhir'), 'state-start-end',
      text('A filled circle selects the starting state; a bullseye terminates the state machine.', 'Bulatan berisi memilih keadaan permulaan; bulatan sasaran menamatkan mesin keadaan.'),
      text('Follow the initial transition into the first named state.', 'Ikuti peralihan awal ke keadaan bernama pertama.'),
      text('Use final only when that object’s lifecycle is complete.', 'Gunakan final hanya apabila kitar hayat objek selesai.'),
      text('Do not assume every state machine needs a final state.', 'Jangan anggap setiap mesin keadaan memerlukan keadaan akhir.'),
      { aliases: ['initial state', 'final state', 'keadaan awal', 'keadaan akhir'] }),
    topic('state', 'transition', text('Transition', 'Peralihan'), 'state-transition',
      text('A directed transition changes the active state when its trigger and guard allow it.', 'Peralihan berarah mengubah keadaan aktif apabila pencetus dan guard membenarkannya.'),
      text('Read from source state to target state.', 'Baca dari keadaan sumber kepada keadaan sasaran.'),
      text('Use it for meaningful state changes.', 'Gunakannya untuk perubahan keadaan yang bermakna.'),
      text('Do not use transitions as arbitrary data-flow arrows.', 'Jangan gunakan peralihan sebagai anak panah aliran data sewenang-wenangnya.'),
      { aliases: ['transition', 'state change', 'peralihan', 'ubah keadaan'] }),
    topic('state', 'event-guard-action', text('event [guard] / action', 'peristiwa [guard] / tindakan'), 'state-label',
      text('A transition label may contain the trigger, an optional guard and an effect action.', 'Label peralihan boleh mengandungi pencetus, guard pilihan dan tindakan kesan.'),
      text('Read `save [valid] / persist()` as trigger, condition, then effect.', 'Baca `save [valid] / persist()` sebagai pencetus, syarat, kemudian kesan.'),
      text('Use only the parts needed for clarity.', 'Gunakan hanya bahagian yang diperlukan untuk kejelasan.'),
      text('Do not confuse the slash with alternatives.', 'Jangan kelirukan garis miring dengan alternatif.'),
      { aliases: ['event guard action', 'trigger', 'effect', 'peristiwa', 'pencetus', 'tindakan'] }),
    topic('state', 'self-transition', text('Self-transition', 'Peralihan kendiri'), 'state-self',
      text('A transition leaves and re-enters the same state while executing its effect.', 'Peralihan meninggalkan dan memasuki semula keadaan sama sambil melaksanakan kesannya.'),
      text('Read it as an event that keeps the state name but still performs transition behaviour.', 'Bacanya sebagai peristiwa yang mengekalkan nama keadaan tetapi masih melaksanakan tingkah laku peralihan.'),
      text('Use it when exit/entry or transition effects genuinely occur.', 'Gunakannya apabila kesan keluar/masuk atau peralihan benar-benar berlaku.'),
      text('It is different from a sequence self-message even though both look like loops.', 'Ia berbeza daripada mesej kendiri jujukan walaupun kedua-duanya kelihatan seperti gelung.'),
      { aliases: ['self transition', 'state loop', 'peralihan kendiri'] }),
  ];

  chapters.forEach((chapter) => { chapter.topicIds = topics.filter((item) => item.chapterId === chapter.id).map((item) => item.id); });

  const quizQuestions = [
    question('orientation', 'orientation-1', text('Which diagram is read primarily from top to bottom as time passes?', 'Rajah manakah dibaca terutamanya dari atas ke bawah mengikut masa?'), [text('Class diagram', 'Rajah kelas'), text('Sequence diagram', 'Rajah jujukan'), text('ERD', 'ERD')], 1, text('Sequence diagrams place time vertically from top to bottom.', 'Rajah jujukan meletakkan masa secara menegak dari atas ke bawah.')),
    question('orientation', 'orientation-2', text('What does `[session exists]` represent?', 'Apakah yang diwakili `[session exists]`?'), [text('A class name', 'Nama kelas'), text('A guard condition', 'Syarat guard'), text('A database key', 'Kekunci pangkalan data')], 1, text('Square brackets contain a condition that controls a path.', 'Kurungan siku mengandungi syarat yang mengawal laluan.')),
    question('connectors', 'connectors-1', text('Which symbol marks composition?', 'Simbol manakah menandakan composition?'), [text('Hollow diamond', 'Berlian kosong'), text('Filled diamond', 'Berlian berisi'), text("Crow's foot", 'Kaki gagak')], 1, text('Composition uses a filled diamond at the owning whole.', 'Composition menggunakan berlian berisi pada keseluruhan yang memiliki.')),
    question('connectors', 'connectors-2', text('Can a dashed line be interpreted without its context?', 'Bolehkah garisan putus-putus ditafsir tanpa konteks?'), [text('Always', 'Sentiasa'), text('No; inspect diagram type and arrowhead', 'Tidak; semak jenis rajah dan kepala anak panah'), text('Only in dark mode', 'Hanya dalam mod gelap')], 1, text('Dashed dependencies, returns, realizations and logical links use different heads and contexts.', 'Dependency, pulangan, realization dan pautan logik putus-putus menggunakan kepala serta konteks berbeza.')),
    question('usecase', 'usecase-1', text('Where does an `extend` arrow point?', 'Ke manakah anak panah `extend` menunjuk?'), [text('Toward the extending use case', 'Ke arah kes guna tambahan'), text('Toward the base use case', 'Ke arah kes guna asas'), text('Toward the actor', 'Ke arah aktor')], 1, text('The extension points back to the complete base use case.', 'Extension menunjuk kembali kepada kes guna asas yang lengkap.')),
    question('usecase', 'usecase-2', text('What belongs outside the system boundary?', 'Apakah yang berada di luar sempadan sistem?'), [text('Actors', 'Aktor'), text('Use cases', 'Kes guna'), text('Included behaviour', 'Tingkah laku include')], 0, text('Actors are external roles; system-provided use cases are inside.', 'Aktor ialah peranan luar; kes guna yang disediakan sistem berada di dalam.')),
    question('sequence', 'sequence-1', text('What does the “U-turn” arrow mean?', 'Apakah maksud anak panah “pusingan U”?'), [text('A returned error', 'Ralat dikembalikan'), text('A participant calls itself', 'Peserta memanggil dirinya'), text('A loop fragment', 'Fragmen loop')], 1, text('It is a sequence self-message or self-call.', 'Ia ialah mesej kendiri atau panggilan kendiri jujukan.')),
    question('sequence', 'sequence-2', text('Which line normally shows a returned value?', 'Garisan manakah biasanya menunjukkan nilai pulangan?'), [text('Dashed with an open head', 'Putus-putus berkepala terbuka'), text('Solid with a filled head', 'Pejal berkepala berisi'), text('Solid with a diamond', 'Pejal dengan berlian')], 0, text('A dashed open message optionally documents a return.', 'Mesej terbuka putus-putus secara pilihan mendokumenkan pulangan.')),
    question('fragments', 'fragments-1', text('Which fragment shows one optional guarded path?', 'Fragmen manakah menunjukkan satu laluan ber-guard pilihan?'), [text('alt', 'alt'), text('opt', 'opt'), text('par', 'par')], 1, text('`opt` runs its single operand only when the guard is true.', '`opt` melaksanakan operand tunggalnya hanya apabila guard benar.')),
    question('fragments', 'fragments-2', text('How should “fetch failed and stale cache exists” be modeled?', 'Bagaimanakah “fetch gagal dan cache lama wujud” patut dimodelkan?'), [text('As a self-message', 'Sebagai mesej kendiri'), text('As an `alt` operand guard', 'Sebagai guard operand `alt`'), text('As composition', 'Sebagai composition')], 1, text('It selects an alternative control path rather than invoking a method on itself.', 'Ia memilih laluan kawalan alternatif dan bukan memanggil kaedah kendiri.')),
    question('activity', 'activity-1', text('Which node chooses one mutually exclusive path?', 'Nod manakah memilih satu laluan yang saling eksklusif?'), [text('Decision diamond', 'Berlian keputusan'), text('Fork bar', 'Bar fork'), text('Final node', 'Nod akhir')], 0, text('A decision uses guarded outputs; a fork starts parallel branches.', 'Keputusan menggunakan output ber-guard; fork memulakan cabang selari.')),
    question('activity', 'activity-2', text('What do swimlanes primarily communicate?', 'Apakah yang terutama disampaikan swimlane?'), [text('Time', 'Masa'), text('Responsibility', 'Tanggungjawab'), text('Cardinality', 'Kardinaliti')], 1, text('Swimlanes partition actions by responsible role or component.', 'Swimlane membahagikan tindakan mengikut peranan atau komponen bertanggungjawab.')),
    question('class', 'class-1', text('Where does the aggregation diamond go?', 'Di manakah berlian aggregation diletakkan?'), [text('At the part', 'Pada bahagian'), text('At the whole', 'Pada keseluruhan'), text('At both ends', 'Pada kedua-dua hujung')], 1, text('Both aggregation and composition diamonds are placed at the whole/owner.', 'Berlian aggregation dan composition diletakkan pada keseluruhan/pemilik.')),
    question('class', 'class-2', text('What does `0..1` mean?', 'Apakah maksud `0..1`?'), [text('Exactly one', 'Tepat satu'), text('Optional, at most one', 'Pilihan, paling banyak satu'), text('Any number', 'Sebarang bilangan')], 1, text('The relationship may be absent or contain one instance.', 'Hubungan boleh tiada atau mengandungi satu instance.')),
    question('erd', 'erd-1', text('What enforces a database foreign key?', 'Apakah yang menguatkuasakan foreign key pangkalan data?'), [text('The diagram color', 'Warna rajah'), text('PostgreSQL/schema constraint', 'Kekangan PostgreSQL/skema'), text('A UI label', 'Label UI')], 1, text('A real FK is a database constraint, unlike an application-only logical link.', 'FK sebenar ialah kekangan pangkalan data, tidak seperti pautan logik aplikasi sahaja.')),
    question('erd', 'erd-2', text('Why use a junction table?', 'Mengapa menggunakan jadual penghubung?'), [text('To resolve many-to-many data', 'Untuk menyelesaikan data banyak-ke-banyak'), text('To draw a lifeline', 'Untuk melukis lifeline'), text('To create inheritance', 'Untuk mencipta inheritance')], 0, text('It turns a many-to-many relation into two one-to-many relations.', 'Ia menukar hubungan banyak-ke-banyak kepada dua hubungan satu-ke-banyak.')),
    question('architecture', 'architecture-1', text('Does a data-flow arrow prove class ownership?', 'Adakah anak panah aliran data membuktikan pemilikan kelas?'), [text('Yes', 'Ya'), text('No', 'Tidak'), text('Only for HTTP', 'Hanya untuk HTTP')], 1, text('Runtime data movement and structural ownership are different claims.', 'Pergerakan data masa jalan dan pemilikan struktur ialah dakwaan berbeza.')),
    question('architecture', 'architecture-2', text('Which relationship best shows a module merely uses a service?', 'Hubungan manakah paling sesuai menunjukkan modul hanya menggunakan servis?'), [text('Composition', 'Composition'), text('Dependency', 'Dependency'), text('Inheritance', 'Inheritance')], 1, text('A dependency states use without claiming lifecycle ownership.', 'Dependency menyatakan penggunaan tanpa mendakwa pemilikan kitar hayat.')),
    question('state', 'state-1', text('What triggers movement between states?', 'Apakah yang mencetuskan pergerakan antara keadaan?'), [text('A transition event', 'Peristiwa peralihan'), text('Multiplicity', 'Multiplicity'), text('A lifeline', 'Lifeline')], 0, text('Events, optionally constrained by guards, trigger transitions.', 'Peristiwa, yang mungkin dikekang guard, mencetuskan peralihan.')),
    question('state', 'state-2', text('Is a state self-transition the same as a sequence self-message?', 'Adakah peralihan kendiri keadaan sama dengan mesej kendiri jujukan?'), [text('Yes', 'Ya'), text('No; they belong to different diagram semantics', 'Tidak; kedua-duanya mempunyai semantik rajah berbeza'), text('Only when dashed', 'Hanya apabila putus-putus')], 1, text('One changes/re-enters state; the other invokes an operation on the same lifeline.', 'Satu mengubah/memasuki semula keadaan; satu lagi memanggil operasi pada lifeline yang sama.')),
  ];

  const labPresets = {
    connector: ['association', 'dependency', 'generalization', 'realization', 'aggregation', 'composition', 'sequence-call', 'sequence-return', 'crow-foot'],
    fragment: ['alt', 'opt', 'loop', 'par', 'break', 'ref'],
    multiplicity: ['0..1', '1', '0..*', '1..*'],
  };

  const sources = {
    ttte1113: { label: text('TTTE1113 Chapter 4, pages 23–28', 'TTTE1113 Bab 4, halaman 23–28'), local: true },
    'omg-uml': { label: text('OMG UML 2.5.1 specification', 'Spesifikasi OMG UML 2.5.1'), href: 'https://www.omg.org/spec/UML' },
    drawio: { label: text('draw.io UML documentation', 'Dokumentasi UML draw.io'), href: 'https://www.drawio.com/docs/diagram-types/uml/' },
    'drawio-sequence': { label: text('draw.io sequence-diagram guide', 'Panduan rajah jujukan draw.io'), href: 'https://www.drawio.com/docs/diagram-types/uml/sequence-diagrams/' },
    'drawio-class': { label: text('draw.io class-diagram guide', 'Panduan rajah kelas draw.io'), href: 'https://www.drawio.com/docs/diagram-types/uml/class-diagrams/' },
  };

  window.PETAKERJA_LEARNING = { chapters, topics, quizQuestions, labPresets, sources };
}());
